<!DOCTYPE html>
<html>

<head>
    <title>REQUEST GENERATE VOUCHER</title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            text-align: center;
            font-size: 14px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
    @if(SettingsFacade::data()->UnRegisteredTitle !=0)
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    @endif
    <h3>
        <center>REQUEST GENERATE VOUCHER</center>
    </h3>

    <hr /><br />
    <div style="clear:both">
        <div style="float: left;"><b>Dept: </b>@if($RequestGenerateDetails[0]->request_generate->warehouse){{ $RequestGenerateDetails[0]->request_generate->warehouse->name }} @else{{ "No Dept" }}@endif</div>

    </div>
    <div style="clear:both">
        <div style="float: left;"><b>Voucher.No: </b>{{ $RequestGenerateDetails[0]->request_generate->bill_no }}</div>
        <div style="float: right;"><b>Voucher
                Date: </b>{{ date('d/m/Y', strtotime($RequestGenerateDetails[0]->request_generate->date)) }}</div>
    </div>
    <br />
    <div style="clear:both">
        <div style="float:left;"><b>Supplier: </b>@if($RequestGenerateDetails[0]->request_generate->supplier) {{  $RequestGenerateDetails[0]->request_generate->supplier->party_name  }}
            @else{{ "No Supplier" }}
            @endif
        </div>
         <div style="float:right;"><b>Purchaser:</b> @if($RequestGenerateDetails[0]->request_generate->purchaser){{  $RequestGenerateDetails[0]->request_generate->purchaser->party_name  }}
            @else{{ "No Purchaser" }}
            @endif
        </div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Remarks: </b>@if($RequestGenerateDetails[0]->request_generate) {{  $RequestGenerateDetails[0]->request_generate->remarks }}
            @else{{ "No Remarks" }}
            @endif
        </div>
    </div>
    <br /><br />
     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>  
                <th>Code</th>
                <th>Product</th>
                <th>Unit</th>
                <th>Total Qty</th>
                <th>Comment</th>
            </tr>
        </thead>
        <tbody>
            @php $total=0; @endphp
            @foreach ($RequestGenerateDetails as $value)
                <tr>
                    <td>@if($value->product){{ $value->product->code }} @else{{ 'NO Code' }} @endif</td> 
                     <td>@if($value->product){{ $value->product->product_name }} @else{{ 'NO Product' }}@endif</td> 
                     <td>@if($value->product){{ $value->product->uom }} @else{{ 'NO Unit' }} @endif</td> 
                    <td>{{ $value->qty }}</td>
                    <td>{{ $value->comments }}</td>
                </tr>
                 @php $total+=$value->qty; @endphp
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="2">Total</th>
                <th></th>
                <th>{{ number_format($total,2) }}</th>
                <th></th>

            </tr>
        </tfoot>
    </table>
    @include('include.numberconvert')
  <span style="text-transform: capitalize; float:right">Qty In Words: {{ convertNumber($total) }} Only</span>

    <br />
    <br />
    <table>
        <tbody>
            <tr>
                <td colspan="5">Generated by:<b><u>{{ $RequestGenerateDetails[0]->request_generate->user->name }}</u></b></td>
                <td>Checked by:________________</td>
                <td>Approved by:_______________</td>
            </tr>
            <tr>
                <td colspan="5">Print Date:{{ date('d/m/Y') }}, {{ date('h:i:s A') }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>
