<!DOCTYPE html>
<html>

<head>
    <title>OPENING STOCK VOUCHER</title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            text-align: center;
            font-size: 14px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
@if(SettingsFacade::data()->UnRegisteredTitle !=0)
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    @endif
    <h3>
        <center>OPENING STOCK VOUCHER</center>
    </h3>
    <hr /><br />
    <div style="clear:both">
        <div style="float: left;"><b>Voucher.No: </b>{{ $stockdetail[0]->voucher_no }}</div>
        <div style="float: right;"><b>Voucher
                Date: </b>{{ date('d/m/Y', strtotime($stockdetail[0]->date)) }}</div>
    </div>
    <br />
    <div style="clear:both">
        <div style="float:left;"><b>Warehouse: </b> {{  $stockdetail[0]->warehouse->name}}</div>
         <div style="float:right;"><b>Remarks:</b> {{  $stockdetail[0]->remarks }}</div>
    </div>
    <br /><br />
     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr style="border:2px solid;">  
                <th>Sr</th>
                <th>Code</th>
                <th style="text-align:left;">Product Name</th>
                <th>Unit</th>
                <th>Packing</th>
                <th>Qty</th>
                <th>Pack Qty</th>
                <th>Rate</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody>
            @php $totalqty=0; $totalPackqty=0; $grandPackqty=0; $totalrate=0; $totalamount=0; @endphp
            @foreach ($stockdetail[0]->godown_stock_details as $value)
            @if($value->product)
            @php $totalPackqty = $value->qty_in/$value->product->packing; @endphp
                <tr style="border-bottom: 1px solid;">
                     <td>{{ $loop->iteration }}</td> 
                     <td>{{ $value->product->code }}</td> 
                     <td style="text-align:left;">&nbsp;{{ $value->product->product_name }}</td> 
                     <td>{{ $value->product->uom }}</td>
                     <td>{{ number_format($value->product->packing) }}</td> 
                    <td style="text-align:right;">{{ number_format($value->qty_in) }}</td>
                    <td>{{ number_format($totalPackqty, 2) }}</td> 
                    <td>{{ $value->sale_rate }}</td>
                    <td style="text-align:right;">{{ number_format($value->amount) }}</td>
                </tr>
                 @php
                  $totalqty+=$value->qty_in; 
                  $totalrate+=$value->sale_rate; 
                  $totalamount+=$value->amount; 
                  $grandPackqty+=$totalPackqty; 
                 @endphp
                 @endif
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="5">Total</th>
               
                <th style="text-align:right;">{{ number_format($totalqty,2) }}</th>
                <th>{{ number_format($grandPackqty, 3) }}</th>
                <th></th>
                <th style="text-align:right;">{{ number_format($totalamount) }}</th>
              

            </tr>
        </tfoot>
    </table>
    <br />
    <table>
        <tbody>
            <tr>
                <td colspan="5">Generated by:<b><u>{{ $stockdetail[0]->generated_by->name}}</u></b></td>
                <td>Checked by:________________</td>
                <td>Approved by:_______________</td>
            </tr>
            <tr>
                <td colspan="5">Print:{{ date('d/m/Y') }}, Time: {{ date('h:i:s A') }}</td>
            </tr>
        </tbody>
    </table>
    
</body>

</html>
