<!DOCTYPE html>
<html>

<head>
    <title>RECIPE CREATION</title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            text-align: center;
            font-size: 14px;
        }

        #designed tbody tr td{
            border-top: 0px!important;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    <h3>
        <center>RECIPE CREATION</center>
    </h3>
    <hr /><br />
    <div style="clear:both">
        <div style="float: left;"><b>Voucher.No: </b>{{ $recipecreationdetails[0]->recipe_creation->voucher_no }}</div>
        <div style="float: right;"><b>Voucher
                Date: </b>{{ date('d/m/Y', strtotime($recipecreationdetails[0]->recipe_creation->date)) }}</div>
    </div>
    <br />
    <div style="clear:both">
        <div style="float:left;"><b>Product: </b> {{ $recipecreationdetails[0]->recipe_creation->product->product_name }}
        </div>
        <div style="float:right;"><b>Unit:</b> {{ $recipecreationdetails[0]->recipe_creation->product->uom }}</div>
    </div>
    <div style="clear:both">
        <!-- <div style="float:left;"><b>Product Code: </b> {{ $recipecreationdetails[0]->recipe_creation->recipe_code }} -->
        <div style="float:left;"><b>Product Code: </b> {{ $recipecreationdetails[0]->recipe_creation->product->code }}
        </div>
        <div style="float:right;"><b>Godown: </b>
            @if ($recipecreationdetails[0]->recipe_creation->warehouse)
                {{ $recipecreationdetails[0]->recipe_creation->warehouse->name }}
            @endif
        </div>
    </div>
    <br /><br />
    <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>
                <th>Code</th>
                <th>Product</th>
                <th>Unit</th>
                <th>Total Qty</th>
                <th>Wastage</th>
                <th>Total Rate</th>
                <th>Total Amount</th>
            </tr>
        </thead>
        <tbody>
            @php
                $totalqty = 0;
                $totalrate = 0;
                $totalamount = 0;
            @endphp
            @foreach ($recipecreationdetails as $value)
                <tr>
                    <td>{{ $value->product->code }}</td>
                    <td>{{ $value->product->product_name }}</td>
                    <td>{{ $value->product->uom }}</td>
                    <td>{{ number_format($value->quantity, 4) }}</td>
                    <td>{{ $value->wastage }}</td>
                    <td>{{ number_format($value->rate, 2) }}</td>
                    <td>{{ $value->amount }}</td>
                </tr>
                @php
                    $totalqty += $value->quantity;
                    $totalrate += $value->rate;
                    $totalamount += $value->amount;
                @endphp
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="3">Total</th>
                <th>{{ number_format($totalqty, 2) }}</th>
                <th></th>
                <th>{{ number_format($totalrate, 2) }}</th>
                <th>{{ $totalamount }}</th>
            </tr>
        </tfoot>
    </table>
    <br />
    <table>
        <tbody>
            <tr>
                <td colspan="4">Generated by:<b><u>{{ $recipecreationdetails[0]->recipe_creation->generated_by->name }}</u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Checked by:________________</td>
                <td>Approved by:_______________</td>
            </tr>
            <tr>
                <td colspan="5">Print Date:{{ date('d/m/Y') }} Time: {{ date('h:i:s A') }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>
