<!DOCTYPE html>
<html>

<head>
    <title> SLITTING STOCK TRANSFER </title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            /* text-align: center; */
            font-size: 14px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    <h3>
        <center>SLITTING STOCK TRANSFER</center>
    </h3>
    <hr /><br />

    <div style="clear:both">
        <div style="float:left;"><b>Voucher No: {{$production[0]->voucher_no}}</b></div>
         <div style="float:right;"><b>Voucher Date: {{date("d/m/Y", strtotime($production[0]->date))}}</b> </div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Transfer From: {{$production[0]->warehouse_from->name}}</b></div>
         <div style="float:right;"><b>Transfer To: {{$production[0]->warehouse_to->name}}</b> </div>
    </div>

    <div style="clear:both">
        <div style="float:left;"><b>Remarks: </b>{{$production[0]->remarks}} </div>
        <!-- <div style="float:right;"><b>Remarks: </b> </div> -->
    </div><br />
     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>  
                <th>Sr#</th>
                <th align="left">Product Name</th>
                <th>Unit</th>
                <th>Thickness</th>
                <th>Width</th>
                <th>Length</th>
                <th>Qty</th>
                <th>Packing</th>
                <th>Weight</th>
            </tr>
        </thead>
        <tbody>
            @php $sum=0; $weight=0; $quantity=0; @endphp
            @foreach($production[0]->slitting_production_details as $data)
            @php 
            $sum= $sum + 1; 
            $weight= $weight + $data->weight; 
            $quantity= $quantity + $data->qty; 
            @endphp
                <tr>
                    <td align="center">{{$sum}}</td>
                    <td>{{$data->product->product_name}}</td> 
                    <td align="center">{{$data->product->uom}}</td>
                    <td align="center">{{$data->thickness}}</td>
                    <td align="center">{{$data->width}}</td>
                    <td align="center">{{$data->length}}</td>
                    <td align="center">{{$data->qty}}</td>
                    <td align="center">{{$data->packing}}</td>
                    <td align="center">{{$data->weight}}</td>
                </tr>
                @endforeach

        </tbody>
        <tfoot>
            <tr align="center">
                <th colspan="6">Total</th>
                <th>{{number_format($quantity)}}</th>
                <th></th>
                <th>{{number_format($weight)}}</th>
            </tr>
        </tfoot>
    </table>
    <br />
    <table>
        <tbody>
            <!-- <tr>
                <td>Signature: __________</td>
            </tr><br />
            <tr>
                <td>Name & Designation: __________</td>
            </tr> -->
            <tr>
                <td>Generated by:<b><u>{{$production[0]->generated_by->name}}
                  
                
                </u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Checked by:<b><u></u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Approved by:<b><u></u></b></td>
            </tr>
            <tr>
                <td colspan="5">Print:{{ date('d/m/Y') }}  {{ date('h:i:s A') }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>
