<!DOCTYPE html>
<html>

<head>
    <title>PRODUCTION REPORT</title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            /* text-align: center; */
            font-size: 14px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    <h3>
        <center>PRODUCTION REPORT</center>
    </h3>
    <p style="text-align: center;"><span>From: {{date("d/m/Y", strtotime($fromDate))}} To: {{date("d/m/Y", strtotime($toDate))}}</p>
    <hr /><br />

     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>  
                <th>Sr#</th>
                <th>Date</th>
                <th>Batch.NO</th>
                <th>Code</th>
                <th>Product Name</th>
                <th>Recipe</th>
                <th>Color</th>
                <th>Machine</th>
                <th>Shift</th>
                <th>Forman</th>
                <th>Operator</th>
                <th>Thickness</th>
                <th>Width</th>
                <th>Net Weight</th>
            </tr>
        </thead>
        <tbody>
            @php $sum=1; $totalqty=0; @endphp
            @foreach($data as $data1)
                <tr>
                    <td align="center">{{$sum}}</td>
                    <td>{{date("d/m/Y", strtotime($data1->date))}}</td> 
                    <td>{{$data1->production->batchNo}}</td>
                    <td>{{$data1->product->code}}</td>
                    <td style="font-size:10px;">{{$data1->product->product_name}}</td>
                    <td style="font-size:10px;">{{$data1->production->recipe->recipe_name}}</td>
                    <td>
                        @if($data1->production->color)
                        {{$data1->production->color->name}}
                        @endif
                    </td>
                    <td>
                    @if($data1->production->machine)
                    {{$data1->production->machine->machine_name}}
                    @endif
                    </td>
                    <td>
                    @if($data1->production->shift)
                    {{$data1->production->shift->shift_name}}
                    @endif
                    </td>
                    <td style="font-size:10px;">
                    @if($data1->production->forman)
                    {{$data1->production->forman->party_name}}
                    @endif
                    </td>
                    <td style="font-size:10px;">
                    @if($data1->production->operator)
                    {{$data1->production->operator->party_name}}
                    @endif
                    </td>
                    <td>{{$data1->production->thickness}}</td>
                    <td>{{$data1->production->width}}</td>
                    <td>{{number_format($data1->qty_in, 2)}}</td>
                </tr>
                @php 
                $sum=$sum + 1;
                $totalqty= $totalqty + $data1->qty_in; 
                @endphp
            @endforeach

        </tbody>
        <tfoot>
            <tr align="center">
                <th colspan="13">Total</th>
                <th>{{number_format($totalqty, 2)}}</th>
                
            </tr>
        </tfoot>
    </table>
    <br />
    <table>
        <tbody>

            <tr>
                <td>Generated by: {{Auth::User()->name}}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Checked by:<b><u></u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Approved by:<b><u></u></b></td>
            </tr>
            <tr>
                <td colspan="5">Print:{{ date('d/m/Y') }}  {{ date('h:i:s A') }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>
