<!DOCTYPE html>
<html>

<head>
    <title> PACKING PRODUCTION REPORT </title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            /* text-align: center; */
            font-size: 10px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 10px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 10px;
        }
    </style>
</head>

<body>
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    <h3>
        <center>PACKING PRODUCTION REPORT</center>
    </h3>
    <hr /><br />

    <!-- <div style="clear:both">
        <div style="float:left;"><b>Voucher No: </b></div>
         <div style="float:right;"><b>Voucher Date:</b>  </div>
    </div> -->
    <!-- <div style="clear:both">
        <div style="float:left;"><b>Remarks: </b> 3</div>
    </div>
    <br /><br /> --><br />
     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>  
                <th>Date</th>
                <th align="left">Batch#</th>
                <!-- <th>Thick Width</th> -->
                <th>Net Weight</th>
                <th>Consumed</th>
                <th>Color</th>
                <th>Product&nbsp;Name&nbsp;&&nbsp;SKU</th>
                <th>Dye PCS</th>
                <th>Oper ID</th>
                <th>Machine</th>
                <th>PM ID</th>
                <th>P No</th>
                <th>Sheets</th>
                <th>Check</th>
                <th>Waste</th>
                <th>Net S</th>
                <th>Net SKU</th>
            </tr>
        </thead>
        <tbody>
            @php
                $sum = 0;
                $NetWeight = 0;
                $Consumed = 0;
                $TotalSheets = 0;
                $CheckSheets = 0;
                $Wastage = 0;
                $NetSheets = 0;
                $NetSKU = 0;
            @endphp
            @foreach($production as $data)
            @php
            $NetWeight = $NetWeight + 1;
            @endphp
                <tr>
                    <td style="font-size: 10px;" align="center">0</td>
                    <td style="font-size: 8px !important;">2
                    <br/>
                    1
                    </td> 
                    <td align="center">4</td>
                    <td align="center">5</td>
                    <td align="center">6</td>
                    <td style="font-size: 8px !important;">7</td>
                    <td align="center">8</td>
                    <td align="center">9</td>
                    <td align="center">10</td>
                    <td align="center">1</td>
                    <td align="center">2</td>
                    <td align="center">3</td>
                    <td align="center">4</td>
                    <td align="center">5</td>
                    <td align="center">6</td>
                    <td align="center">7</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr align="center">
                <th colspan="2">Total</th>
               
                <th>1</th>
                <th>2</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th>3</th>
                <th>4</th>
                <th>5</th>
                <th>6</th>
                <th>7</th>
            </tr>
        </tfoot>
    </table>
    <br />
    <table>
        <tbody>
            <!-- <tr>
                <td>Signature: __________</td>
            </tr><br />
            <tr>
                <td>Name & Designation: __________</td>
            </tr> -->
            <tr>
                <td>Generated by:<b><u>{{Auth::user()->name}}
                  
                
                </u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Checked by:<b><u></u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Approved by:<b><u></u></b></td>
            </tr>
            <tr>
                <td colspan="5">Print:{{ date('d/m/Y') }}  {{ date('h:i:s A') }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>
