<!DOCTYPE html>
<html>

<head>
    <title> PACKING PRODUCTION</title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            /* text-align: center; */
            font-size: 14px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    <h3>
        <center>PACKING PRODUCTION</center>
    </h3>
    <hr /><br />

    <div style="clear:both">
        <div style="float:left;"><b>Voucher No: {{$production->voucher_no}}</b></div>
         <div style="float:right;"><b>Voucher Date: {{date("d/m/Y", strtotime($production->date))}}</b> </div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Batch No: {{$production->thermoforming_production->roll_production->batchNo}}</b> </div>
        <div style="float:right;"><b>Product Name: {{$production->thermoforming_production->product->product_name}}</b></div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Shift: </b>{{$production->thermoforming_production->shift->shift_name}}</div>
        <div style="float:right;"><b>Operator: </b> {{$production->thermoforming_production->operator->party_name}}</div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Machine: </b> {{$production->thermoforming_production->machine->machine_name}}</div>
        <div style="float:right;"><b>Pressman: </b> {{$production->thermoforming_production->pressman->party_name}}</div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Press No: </b> {{$production->thermoforming_production->pressman_no}}</div>
        <div style="float:right;"><b>Total Sheets: </b> {{$production->thermoforming_production->total_sheets}}</div>
    </div>


    <div style="clear:both">
        <div style="float:left;"><b>Check Sheets: </b> {{$production->thermoforming_production->check_sheets}}</div>
        <div style="float:right;"><b>Wastage: </b> {{$production->thermoforming_production->wastage}}</div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Net Sheets: </b> {{$production->thermoforming_production->net_sheets}}</div>
        <div style="float:right;"><b>Net SKU: </b> {{$production->thermoforming_production->net_sku}}</div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Product Name: </b> {{$production->product->product_name}}</div>
        <div style="float:right;"><b>Packing: </b> {{$production->product->packing}}</div>
    </div>
    <!-- <div style="clear:both">
        <div style="float:left;"><b>Press No: </b> </div>
        <div style="float:right;"><b>Total Sheets: </b> </div>
    </div> -->
    <div style="clear:both">
        <div style="float:left;"><b>Remarks: </b> {{$production->remarks}}</div>
        <!-- <div style="float:right;"><b>Remarks: </b> </div> -->
    </div><br />
     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>  
                <th>Sr#</th>
                <th align="left">Employee Name</th>
                <th>Quantity</th>
                <th>Pieces</th>
            </tr>
        </thead>
        <tbody>
            @php $sum=1; $totalqty=0; $totalpcs=0; @endphp
            @foreach($production->packing_production as $data)
                <tr>
                    <td align="center">{{$sum}}</td>
                    <td>{{$data->employee->party_name}}</td> 
                    <td align="center">{{$data->qty}}</td>
                    <td align="center">{{$data->pcs}}</td>
                </tr>
                @php 
                $sum=$sum + 1;
                $totalqty= $totalqty + $data->qty; 
                $totalpcs= $totalpcs + $data->pcs; 
                @endphp
            @endforeach

        </tbody>
        <tfoot>
            <tr align="center">
                <th colspan="2">Total</th>
                <th>{{number_format($totalqty)}}</th>
                <th>{{number_format($totalpcs)}}</th>
            </tr>
        </tfoot>
    </table>
    <br />
    <table>
        <tbody>
            <!-- <tr>
                <td>Signature: __________</td>
            </tr><br />
            <tr>
                <td>Name & Designation: __________</td>
            </tr> -->
            <tr>
                <td>Generated by:<b><u>{{$production->prepared_by->name}}
                </u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Checked by:<b><u></u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Approved by:<b><u></u></b></td>
            </tr>
            <tr>
                <td colspan="5">Print:{{ date('d/m/Y') }}  {{ date('h:i:s A') }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>
