<!DOCTYPE html>
<html>

<head>
    <title> OPENING STOCK PET ROLLS </title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            /* text-align: center; */
            font-size: 14px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    <h3>
        <center>OPENING STOCK PET ROLLS</center>
    </h3>
    <hr /><br />

    <div style="clear:both">
        <div style="float:left;"><b>Voucher No: </b>{{$production[0]->voucher_no}} </div>
         <div style="float:right;"><b>Voucher Date:</b>{{date("d/m/Y", strtotime($production[0]->date))}} </div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Warehouse Name: </b> {{$production[0]->warehouse->name}} </div>
        <!-- <div style="float:right;"><b>Remarks: </b>{{$production[0]->remarks}} </div> -->
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Remarks: </b> {{$production[0]->remarks}} </div>
        <!-- <div style="float:right;"><b>Remarks: </b>{{$production[0]->remarks}} </div> -->
    </div><br />
     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>  
                <th>Sr#</th>
                <th align="left">Product Name</th>
                <th>Batch.No</th>
                <th>Thickness</th>
                <th>Width</th>
                <th>Color</th>
                <th>Gross Weight</th>
                <th>Net Weight</th>
            </tr>
        </thead>
        <tbody>
            @php $sum = 1; $totalgrass = 0; $totalnet = 0; @endphp
            @foreach($production[0]->opening_pet_rolls as $data)
                <tr>
                    <td align="center">{{$sum}}</td>
                    <td>{{$data->product->product_name}}</td> 
                    <td align="center">{{$data->batchNo}}</td>
                    <td align="center">{{$data->thickness}}</td>
                    <td align="center">{{$data->width}}</td>
                    <td align="center">{{$data->color}}</td>
                    <td align="center">{{$data->gross_weight}}</td>
                    <td align="center">{{$data->net_weight}}</td>
                </tr>
                @php 
                $sum = $sum + 1; 
                $totalgrass = $totalgrass + $data->gross_weight; 
                $totalnet = $totalnet + $data->net_weight; 
                @endphp
            @endforeach
        </tbody>
        <tfoot>
            <tr align="center">
                <th colspan="6">Total</th>
                <th>{{number_format($totalgrass)}}</th>
                <th>{{number_format($totalnet)}}</th>
            </tr>
        </tfoot>
    </table>
    <br />
    <table>
        <tbody>
            <!-- <tr>
                <td>Signature: __________</td>
            </tr><br />
            <tr>
                <td>Name & Designation: __________</td>
            </tr> -->
            <tr>
                <td>Generated by:<b><u>{{$production[0]->generated_by->name}}
                  
                
                </u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Checked by:<b><u></u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Approved by:<b><u></u></b></td>
            </tr>
            <tr>
                <td colspan="5">Print:{{ date('d/m/Y') }}  {{ date('h:i:s A') }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>
