<!DOCTYPE html>
<html>

<head>
    <title> STOCK TRANSFER VOUCHER </title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            text-align: center;
            font-size: 14px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <h1><center>{{ SettingsFacade::data()->title }}</center></h1>
    <h3><center>STOCK TRANSFER VOUCHER</center></h3>
    <hr /><br />
    <div style="clear:both">
        <div style="float: left;"><b>Voucher.No: </b>{{ $godownStockDetail[0]->voucher_no }}</div>
        <div style="float: right;"><b>Voucher
                Date: </b>{{ date('d/m/Y', strtotime($godownStockDetail[0]->date)) }}</div>
    </div>
    <br />
    <div style="clear:both">
        <div style="float:left;"><b>From: </b> {{  $godownStockDetail[0]->warehouse_from->name  }}</div>
         <div style="float:right;"><b>To:</b> {{  $godownStockDetail[0]->warehouse_to->name  }}</div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Remarks: </b> {{  $godownStockDetail[0]->remarks }}</div>
    </div>
    <br /><br />
     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>  
                <th>Code</th>
                <th style="text-align:left;">Product Name</th>
                <th>Unit</th>
                <th>Qty</th>
                <th style="display:none;">Total Rate</th>
                <th style="display:none;">Total Amount</th>
                <th>Packing</th>
                <th>Pack</th>
            </tr>
        </thead>
        <tbody>
            @php $totalqtyout=0;  $totalrate=0; $totalamount=0; $totalpack = 0; @endphp
            @foreach ($godownStockDetail[0]->godown_stock_details as $value)
                <tr style="border-bottom: 1px solid;">
                    <td>{{ $value->product->code }}</td> 
                     <td style="text-align:left;">{{ $value->product->product_name }}</td> 
                     <td>{{ $value->product->uom }}</td>
                    <td>{{ number_format($value->qty_out, 2) }}</td>
                    <td style="display:none;">{{ $value->rate, 2}}</td>
                    <td style="display:none;">{{ $value->amount, 2 }}</td>
                    <td>{{ number_format($value->product->packing) }}</td> 
                    @if($value->product->packing > 0)
                    @php
                    $totalpack = $value->qty_out / $value->product->packing;
                    $totalamount+=$totalpack; 
                    @endphp
                    <td>{{ number_format($totalpack) }}</td> 
                    @else
                    <td>0</td> 
                    @endif
                </tr>
                 @php
                  $totalqtyout+=$value->qty_out; 
                  $totalrate+=$value->rate; 
                 
                 @endphp
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="2">Total</th>
                <th></th>
                <th>{{ number_format($totalqtyout, 2) }}</th>
                <!-- <th>{{ number_format($totalrate,2) }}</th> -->
                <th></th>
                <th>{{ number_format($totalamount, 2) }}</th>
              

            </tr>
        </tfoot>
    </table>
    @include('include.numberconvert')
    <!-- <span style="text-transform: capitalize; float:right">Rupees: {{ convertNumber($totalamount) }}</span>
      <br /> -->
      <table>
          <tbody>
              <tr>
                  <td colspan="5">Generated by:<b><u>{{ $godownStockDetail[0]->user->name }}</u></b></td>
                  <td>Checked by:________________</td>
                  <td>Approved by:_______________</td>
              </tr>
              <tr>
                  <td colspan="8">Print Date: {{ date('d/m/Y') }} Time: {{ date('h:i:s A') }}</td>
              </tr>
          </tbody>
      </table>
  </body>
  
  </html>
