<!DOCTYPE html>
<html>

<head>
    <title>ISSUANCE RETURN VOUCHER </title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            text-align: center;
            font-size: 14px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    <h3>
        <center>ISSUANCE RETURN VOUCHER</center>
    </h3>
    <hr /><br />
    <div style="clear:both">
        <div style="float: left;"><b>Voucher.No: </b>{{ $godownStockDetail[0]->godownstock->voucher_no }}</div>
        <div style="float: right;"><b>Voucher
                Date: </b>{{ date('d/m/Y', strtotime($godownStockDetail[0]->godownstock->date)) }}</div>
    </div>
    <br />
    <div style="clear:both">
        <div style="float:left;"><b>From: </b> {{  $godownStockDetail[0]->godownstock->warehouse_from->name  }}</div>
         <div style="float:right;"><b>To:</b> {{  $godownStockDetail[0]->godownstock->warehouse_to->name  }}</div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Remarks: </b> {{  $godownStockDetail[0]->godownstock->remarks }}</div>
    </div>
    <br /><br />
     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>  
                <!-- <th>Code</th> -->
                <th style="text-align: left;">Product Name</th>
                <th>Unit</th>
                <th style="text-align: left;">Account Name</th>
                <th>Qty</th>
                <th>Total Rate</th>
                <th>Total Amount</th>
            </tr>
        </thead>
        <tbody>
            @php $totalqtyout=0;  $totalrate=0; $totalamount=0; @endphp
            @foreach ($godownStockDetail as $value)
                <tr>
                    <!-- <td></td>  -->
                     <td style="text-align: left; font-size: 12px;">{{ $value->product->code }} - {{ $value->product->product_name }}</td> 
                     <td>{{ $value->product->uom }}</td>
                     <td style="text-align: left; font-size: 12px;">{{ $value->party->code }} - {{ $value->party->party_name }}</td>
                    <td>{{ number_format($value->qty_in, 2) }}</td>
                    <td>{{ number_format($value->rate, 2) }}</td>
                    <td>{{ number_format($value->amount, 2) }}</td>
                </tr>
                 @php
                  $totalqtyout+=$value->qty_in; 
                  $totalrate+=$value->rate; 
                  $totalamount+=$value->amount; 
                 @endphp
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="2">Total</th>
                <th></th>
                <th>{{ number_format($totalqtyout, 2) }}</th>
                <th>{{ number_format($totalrate,2) }}</th>
                <th>{{ number_format($totalamount, 2) }}</th>
              

            </tr>
        </tfoot>
    </table>
    @include('include.numberconvert')
    <span style="text-transform: capitalize; float:right">Rupees: {{ convertNumber($totalamount) }}</span>
      <br />
      <table>
          <tbody>
              <tr>
                  <td colspan="5">Generated by:<b><u>{{ $godownStockDetail[0]->godownstock->user->name }}</u></b></td>
                  <td>Checked by:________________</td>
                  <td>Approved by:_______________</td>
              </tr>
              <tr>
                  <td colspan="5">Print:{{ date('d-M-y') }},{{ date('h:i:s A') }}</td>
              </tr>
          </tbody>
      </table>
  </body>
  
  </html>
