<!DOCTYPE html>
<html>

<head>
    <title> PRODUCTION </title>
    <style>
        #designed {
            border-collapse: collapse;
        }

        #designed thead tr th,
        #designed tbody tr td {
            border-right: 1px solid black;
            /* text-align: center; */
            font-size: 14px;
        }

        #designed thead tr th {
            border-bottom: 1px solid black;
            font-size: 14px;
        }

        #designed tfoot tr th {
            border-top: 1px solid black;
            border-right: 1px solid black;
            font-size: 14px;
        }
    </style>
</head>

<body>
    <h1>
        <center>{{ SettingsFacade::data()->title }}</center>
    </h1>
    <h3>
        <center>THERMOFORMING PRODUCTION</center>
    </h3>
    <hr /><br />

    <div style="clear:both">
        <div style="float:left;"><b>Voucher No: </b>{{$production->voucher_no}} </div>
         <div style="float:right;"><b>Voucher Date:</b> {{$production->voucher_date}} </div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Product Name: </b> {{$production->product->product_name}} </div>
        <div style="float:right;"><b>Dye PCS: </b> {{$production->product->dye_pcs}}</div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Shift: </b> {{$production->shift->shift_name}}</div>
        <div style="float:right;"><b>Operator: </b>{{$production->operator->party_name}}</div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Machine: </b> {{$production->machine->machine_name}}
    </div>
        <div style="float:right;"><b>Pressman: </b>{{$production->pressman->party_name}}
    </div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Press No: </b>{{$production->pressno}}
    </div>
        <div style="float:right;"><b>Total Sheets: </b>{{$production->total_sheets}}
    </div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Check Sheets: </b>{{$production->check_sheets}}
        </div>
        <div style="float:right;"><b>Wastage: </b>{{$production->wastage}}
        </div>
    </div>
    <div style="clear:both">
        <div style="float:left;"><b>Net Sheets  : </b>3{{$production->net_sheets}}
        </div>
        <div style="float:right;"><b>Net SKU: </b> {{$production->net_sku}}
        </div>
    </div>
    <!-- <div style="clear:both">
        <div style="float:left;"><b>Remarks: </b> 3</div>
    </div>
    <br /><br /> --><br />
     <table id="designed" style="border:2px solid; width:100%;">
        <thead>
            <tr>  
                <th>Sr#</th>
                <th align="left">Product Name</th>
                <th>Consumed</th>
                <th>Thickness</th>
                <th>Width</th>
                <th>Net Weight</th>
                <th>Color</th>
            </tr>
        </thead>
        <tbody>

                <tr>
                    <td align="center">1</td>
                    <td>{{$production->roll_production->product->product_name}}</td> 
                    <td align="center">{{$production->consumed}}</td>
                    <td align="center">{{$production->roll_production->thickness}}</td>
                    <td align="center">{{$production->roll_production->width}}</td>
                    <td align="center">{{$production->roll_production->net_weight}}</td>
                    <td align="center">{{$production->roll_production->color}}</td>
                </tr>

        </tbody>
        <!-- <tfoot>
            <tr align="center">
                <th colspan="4">Total</th>
               
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
              

            </tr>
        </tfoot> -->
    </table>
    <br />
    <table>
        <tbody>
            <!-- <tr>
                <td>Signature: __________</td>
            </tr><br />
            <tr>
                <td>Name & Designation: __________</td>
            </tr> -->
            <tr>
                <td>Generated by:<b><u>{{Auth::user()->name}}
                  
                
                </u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Checked by:<b><u></u></b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>Approved by:<b><u></u></b></td>
            </tr>
            <tr>
                <td colspan="5">Print:{{ date('d/m/Y') }}  {{ date('h:i:s A') }}</td>
            </tr>
        </tbody>
    </table>
</body>

</html>
